separate train and test/streaming phases

diff --git a/streamspot-fetch-training-data b/streamspot-fetch-training-data
--- a/streamspot-fetch-training-data
+++ b/streamspot-fetch-training-data
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
-# This script simply reads all available CDM/Avro records from Kafka
-# and writes them to $TRAINING_DIR/train.avro
-
-python fetch_training_data.py \
-  --url $KAFKA_URL_IN \
-  --group $KAFKA_GROUP \
-  --topic $KAFKA_TOPIC_IN \
-  --training-dir $TRAINING_DIR
+# Convert training data from Avro to StreamSpot
+cd /sbustreamspot-cdm
+python translate_cdm_to_streamspot.py \
+  --url $KAFKA_URL_IN --kafka-topic $KAFKA_TOPIC_IN --kafka-group $KAFKA_GROUP \
+  --format avro --source kafka --concise --train > $TRAINING_DIR/train.ss
+if [ $? -ne 0 ]; then
+  echo "[sbustreamspot-cdm] FAIL!"
+  exit 1
+else
+  echo "[sbustreamspot-cdm] SUCCESS"
+fi
